title: djmetzle's Blog
name: djmetzle's Blog
email: djmetzle@ncsu.edu
description: > # this means to ignore newlines until "baseurl:"
  Ramblings about code
github_username: djmetzle
url: http://djmetzle.github.io

# Build settings
theme: jekyll-theme-tactile

# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#
markdown: kramdown
highlighter: rouge

# Includes an icon in the footer for each username you enter
footer-links:
  email:
  facebook:
  github: djmetzle
  instagram:
#  googleplus: # anything in your profile username that comes after plus.google.com/

